---
driver:
  name: ec2
  aws_ssh_key_id: adm_rbroad_dev
  region: eu-west-1
  availability_zone: a
  subnet_id: subnet-f9197f8f
  instance_type: m3.medium
  image_id: ami-a8592cdb
  security_group_ids: ['sg-1aedfa7d']
  retryable_tries: 120

provisioner:
  name: chef_zero

transport:
  ssh_key: C:\Users\Rupert\.ssh\adm_rbroad_dev.pem

platforms:
  - name: windows-2012r2


suites:
  - name: default
    run_list:
      - recipe[cptest::default]
    attributes: